#!/bin/bash
# -*- shell-script -*-
#$  -V
#
#$ -cwd
#
#$ -A A-ccsc
#
#$ -P hpc
#
#$ -N ibrun_t2
#
#$ -j y
#
#$ -o $JOB_NAME.o$JOB_ID
#
#$ -pe 16way 32
#
#$ -q systest
#
#$ -l h_rt=4:00:00


export PATH=$HOME/w/ibrun/src/$TARG:$PATH

for i in `(cd ../src/OBJ; find . -name 'helloCXX')`; do
  echo 
  echo $i
  ibrun tacc_affinity ../src/OBJ/$i
done

