#!/bin/bash
# -*- shell-script -*-

my_hostname=$(hostname -f)
firstName=${my_hostname%%.*}
secondName=${my_hostname#*.}
secondName=${secondName%%.*}

SYSHOST=$secondName

MCLAY_ls4=/home1/00515/mclay
MCLAY_stampede=/home1/00515/mclay

SOURCEME_ls4=sourceme
SOURCEME_stampede=sourceme

eval MCLAY=\$MCLAY_$SYSHOST

for i in $MCLAY/l/pkg/x86_64/luatools/luatools/ \
         $MCLAY/l/pkg/luatools/luatools/ ; do
  if [ -f $i/share/5.1/strict.lua ]; then
    export LUA_PATH="$i/share/5.1/?.lua;;"
    export LUA_CPATH="$i/lib/5.1/?.lua;;"
  fi
done

eval SOURCEME=\$SOURCEME_$SYSHOST

. /root/$SOURCEME

module load lua

$MCLAY/w/ibwrapper/analyze/lariatReport "$@"
